<?php

$title = 'Edit Beer Details';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$brewery_id = $form->get('brewery_id');
$brewery_id->setAttribute('class', 'form-control');
$brewery_id->setAttribute('placeholder', 'Brewery Id');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$cat_id = $form->get('cat_id');
$cat_id->setAttribute('class', 'form-control');
$cat_id->setAttribute('placeholder', 'Category Id');

$style_id = $form->get('style_id');
$style_id->setAttribute('class', 'form-control');
$style_id->setAttribute('placeholder', 'Style Id');


$abv = $form->get('abv');
$abv->setAttribute('class', 'form-control');
$abv->setAttribute('placeholder', 'Abv');


$ibu = $form->get('ibu');
$ibu->setAttribute('class', 'form-control');
$ibu->setAttribute('placeholder', 'Ibu');

$srm = $form->get('srm');
$srm->setAttribute('class', 'form-control');
$srm->setAttribute('placeholder', 'Srm');

$upc = $form->get('upc');
$upc->setAttribute('class', 'form-control');
$upc->setAttribute('placeholder', 'Upc');

$filepath = $form->get('filepath');
$filepath->setAttribute('class', 'form-control');
$filepath->setAttribute('placeholder', 'Filepath');

$descript = $form->get('descript');
$descript->setAttribute('class', 'form-control');
$descript->setAttribute('placeholder', 'Descript');

$add_user = $form->get('add_user');
$add_user->setAttribute('class', 'form-control');
$add_user->setAttribute('placeholder', 'Add User');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('beer', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($brewery_id) ?>
    <?= $this->formElement($brewery_id) ?>
    <?= $this->formElementErrors()->render($brewery_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cat_id) ?>
    <?= $this->formElement($cat_id) ?>
    <?= $this->formElementErrors()->render($cat_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($style_id) ?>
    <?= $this->formElement($style_id) ?>
    <?= $this->formElementErrors()->render($style_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($abv) ?>
    <?= $this->formElement($abv) ?>
    <?= $this->formElementErrors()->render($abv, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($ibu) ?>
    <?= $this->formElement($ibu) ?>
    <?= $this->formElementErrors()->render($ibu, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($srm) ?>
    <?= $this->formElement($srm) ?>
    <?= $this->formElementErrors()->render($srm, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($upc) ?>
    <?= $this->formElement($upc) ?>
    <?= $this->formElementErrors()->render($upc, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($filepath) ?>
    <?= $this->formElement($filepath) ?>
    <?= $this->formElementErrors()->render($filepath, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($descript) ?>
    <?= $this->formElement($descript) ?>
    <?= $this->formElementErrors()->render($descript, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($add_user) ?>
    <?= $this->formElement($add_user) ?>
    <?= $this->formElementErrors()->render($add_user, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();